apiVersion: v1
kind: Service
metadata:
  name: ingestor
  namespace: podmind
  labels:
    app: ingestor
spec:
  selector:
    app: ingestor
  ports:
    - name: http
      port: 8000
      targetPort: http
