apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: sh-core
  labels:
    app: auth
    podmind.component: smarthostel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        podmind.component: smarthostel-service
    spec:
      containers:
        - name: auth
          image: nginx:alpine
          ports:
            - name: http
              containerPort: 80
          env:
            - name: SERVICE_NAME
              value: auth
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet: { path: /, port: http }
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /, port: http }
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/auth
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: auth
