apiVersion: v1
kind: Service
metadata:
  name: booking
  namespace: sh-core
  labels:
    app: booking
spec:
  selector:
    app: booking
  ports:
    - name: http
      port: 80
      targetPort: http
