apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-ingest
  namespace: sh-edge
  labels:
    app: sensor-ingest
    podmind.component: smarthostel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-ingest
  template:
    metadata:
      labels:
        app: sensor-ingest
        podmind.component: smarthostel-service
    spec:
      containers:
        - name: sensor-ingest
          image: nginx:alpine
          ports:
            - name: http
              containerPort: 80
          env:
            - name: SERVICE_NAME
              value: sensor-ingest
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet: { path: /, port: http }
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /, port: http }
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/sensor-ingest
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sensor-ingest
