apiVersion: v1
kind: Service
metadata:
  name: cpu-agent
  namespace: podmind
  labels:
    app: cpu-agent
spec:
  selector:
    app: cpu-agent
  ports:
    - name: http
      port: 8000
      targetPort: http
