apiVersion: v1
kind: Service
metadata:
  name: lock-controller
  namespace: sh-edge
  labels:
    app: lock-controller
spec:
  selector:
    app: lock-controller
  ports:
    - name: http
      port: 80
      targetPort: http
