apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespaces.yaml
  - gateway
  - auth
  - booking
  - room
  - lock-controller
  - sensor-ingest
  - hvac-controller
  - energy-meter
  - billing
  - notifications

commonLabels:
  podmind.tier: smarthostel
